package com.example.ico.trade.okex.util;

import java.util.HashMap;
import java.util.Map;

public class OKEXErrorCode {
    public static Map<String,String> errorCode = new HashMap<>();
    static {
       errorCode.put("20001",	"User does not exist");
       errorCode.put("20002",	"Account frozen");
       errorCode.put("20003",	"Account frozen due to liquidation   ");
       errorCode.put("20004",	"Contract account frozen ");
       errorCode.put("20005",	"User contract account does not exist");
       errorCode.put("20006",	"Required field missing  ");
       errorCode.put("20007",	"Illegal parameter  ");
       errorCode.put("20008",	"Contract account balance is too low ");
       errorCode.put("20009",	"Contract status error   ");
       errorCode.put("20010",	"Risk rate ratio does not exist ");
       errorCode.put("20011",	"Risk rate lower than 90%/80% before opening BTC position with 10x/20x leverage. or risk rate lower than 80%/60% before opening LTC position with 10x/20x leverage  ");
       errorCode.put("20012",	"Risk rate lower than 90%/80% after opening BTC position with 10x/20x leverage. or risk rate lower than 80%/60% after opening LTC position with 10x/20x leverage    ");
       errorCode.put("20013",	"Temporally no counter party price   ");
       errorCode.put("20014",	"System error ");
       errorCode.put("20015",	"Order does not exist    ");
       errorCode.put("20016",	"Close amount bigger than your open positions  ");
       errorCode.put("20017",	"Not authorized/illegal operation    ");
       errorCode.put("20018",	"Order price cannot be more than 103% or less than 97% of the previous minute price ");
       errorCode.put("20019",	"IP restricted from accessing the resource");
       errorCode.put("20020",	"secretKey does not exist");
       errorCode.put("20021",	"Index information does not exist    ");
       errorCode.put("20022",	"Wrong API interface (Cross margin mode shall call cross margin API, fixed margin mode shall call fixed margin API)  ");
       errorCode.put("20023",	"Account in fixed-margin mode   ");
       errorCode.put("20024",	"Signature does not match");
       errorCode.put("20025",	"Leverage rate error");
       errorCode.put("20026",	"API Permission Error    ");
       errorCode.put("20027",	"no transaction record   ");
       errorCode.put("20028",	"no such contract   ");
       errorCode.put("20029",	"Amount is large than available funds");
       errorCode.put("20030",	"Account still has debts ");
       errorCode.put("20038",	"Due to regulation, this function is not availavle in the country/region your currently reside in.  ");
       errorCode.put("20049",	"Request frequency too high");
       errorCode.put("10000",	"Required field, can not be null");
       errorCode.put("10001",	"Request frequency too high to exceed the limit allowed  ");
       errorCode.put("10002",	"System error ");
       errorCode.put("10004",	"Request failed");
       errorCode.put("10005",	"'SecretKey' does not exist    ");
       errorCode.put("10006",	"'Api_key' does not exist ");
       errorCode.put("10007",	"Signature does not match");
       errorCode.put("10008",	"Illegal parameter  ");
       errorCode.put("10009",	"Order does not exist    ");
       errorCode.put("10010",	"Insufficient funds ");
       errorCode.put("10011",	"Amount too low");
       errorCode.put("10012",	"Only btc_usd ltc_usd supported ");
       errorCode.put("10013",	"Only support https request");
       errorCode.put("10014",	"Order price must be between 0 and 1,000,000   ");
       errorCode.put("10015",	"Order price differs from current market price too much  ");
       errorCode.put("10016",	"Insufficient coins balance");
       errorCode.put("10017",	"API authorization error ");
       errorCode.put("10018",	"borrow amount less than lower limit [usd:100,btc:0.1,ltc:1]    ");
       errorCode.put("10019",	"loan agreement not checked");
       errorCode.put("10020",	"rate cannot exceed 1%   ");
       errorCode.put("10021",	"rate cannot less than 0.01%    ");
       errorCode.put("10023",	"fail to get latest ticker ");
       errorCode.put("10024",	"balance not sufficient  ");
       errorCode.put("10025",	"quota is full, cannot borrow temporarily ");
       errorCode.put("10026",	"Loan (including reserved loan) and margin cannot be withdrawn  ");
       errorCode.put("10027",	"Cannot withdraw within 24 hrs of authentication information modification ");
       errorCode.put("10028",	"Withdrawal amount exceeds daily limit    ");
       errorCode.put("10029",	"Account has unpaid loan, please cancel/pay off the loan before withdraw  ");
       errorCode.put("10031",	"Deposits can only be withdrawn after 6 confirmations    ");
       errorCode.put("10032",	"Please enabled phone/google authenticator");
       errorCode.put("10033",	"Fee higher than maximum network transaction fee    ");
       errorCode.put("10034",	"Fee lower than minimum network transaction fee");
       errorCode.put("10035",	"Insufficient BTC/LTC    ");
       errorCode.put("10036",	"Withdrawal amount too low ");
       errorCode.put("10037",	"Trade password not set  ");
       errorCode.put("10040",	"Withdrawal cancellation fails  ");
       errorCode.put("10041",	"Withdrawal address not exsit or approved ");
       errorCode.put("10042",	"Admin password error    ");
       errorCode.put("10043",	"Account equity error, withdrawal failure ");
       errorCode.put("10044",	"fail to cancel borrowing order ");
       errorCode.put("10047",	"this function is disabled for sub-account");
       errorCode.put("10048",	"withdrawal information does not exist    ");
       errorCode.put("10049",	"User can not have more than 50 unfilled small orders (amount<0.15BTC)    ");
       errorCode.put("10050",	"can't cancel more than once    ");
       errorCode.put("10052",	"not allowed to withdraw ");
       errorCode.put("10064",	"after a USD deposit, that portion of assets will not be withdrawable for the next 48 hours    ");
       errorCode.put("10100",	"User account frozen");
       errorCode.put("10101",	"order type is wrong");
       errorCode.put("10102",	"incorrect ID ");
       errorCode.put("10103",	"the private otc order's key incorrect    ");
       errorCode.put("10216",	"Non-available API  ");
       errorCode.put("1002" ,	"The transaction amount exceed the balance");
       errorCode.put("1003" ,	"The transaction amount is less than the minimum requirement    ");
       errorCode.put("1004" ,	"The transaction amount is less than 0    ");
       errorCode.put("1007" ,	"No trading market information  ");
       errorCode.put("1008" ,	"No latest market information   ");
       errorCode.put("1009" ,	"No order");
       errorCode.put("1010" ,	"Different user of the cancelled order and the original order   ");
       errorCode.put("1011" ,	"No documented user ");
       errorCode.put("1013" ,	"No order type");
       errorCode.put("1014" ,	"No login");
       errorCode.put("1015" ,	"No market depth information    ");
       errorCode.put("1017" ,	"Date error   ");
       errorCode.put("1018" ,	"Order failed ");
       errorCode.put("1019" ,	"Undo order failed  ");
       errorCode.put("1024" ,	"Currency does not exist ");
       errorCode.put("1025" ,	"No chart type");
       errorCode.put("1026" ,	"No base currency quantity ");
       errorCode.put("1027" ,	"Incorrect parameter may exceeded limits  ");
       errorCode.put("1028" ,	"Reserved decimal failed ");
       errorCode.put("1029" ,	"Preparing    ");
       errorCode.put("1030" ,	"Account has margin and futures, transactions can not be processed   ");
       errorCode.put("1031" ,	"Insufficient Transferring Balance   ");
       errorCode.put("1032" ,	"Transferring Not Allowed");
       errorCode.put("1035" ,	"Password incorrect ");
       errorCode.put("1036" ,	"Google Verification code Invalid    ");
       errorCode.put("1037" ,	"Google Verification code incorrect  ");
       errorCode.put("1038" ,	"Google Verification replicated ");
       errorCode.put("1039" ,	"Message Verification Input exceed the limit   ");
       errorCode.put("1040" ,	"Message Verification invalid   ");
       errorCode.put("1041" ,	"Message Verification incorrect ");
       errorCode.put("1042" ,	"Wrong Google Verification Input exceed the limit   ");
       errorCode.put("1043" ,	"Login password cannot be same as the trading password   ");
       errorCode.put("1044" ,	"Old password incorrect  ");
       errorCode.put("1045" ,	"2nd Verification Needed ");
       errorCode.put("1046" ,	"Please input old password ");
       errorCode.put("1048" ,	"Account Blocked    ");
       errorCode.put("1201" ,	"Account Deleted at 00: 00 ");
       errorCode.put("1202" ,	"Account Not Exist  ");
       errorCode.put("1203" ,	"Insufficient Balance    ");
       errorCode.put("1204" ,	"Invalid currency   ");
       errorCode.put("1205" ,	"Invalid Account    ");
       errorCode.put("1206" ,	"Cash Withdrawal Blocked ");
       errorCode.put("1207" ,	"Transfer Not Support    ");
       errorCode.put("1208" ,	"No designated account   ");
       errorCode.put("1209" ,	"Invalid api  ");
       errorCode.put("1216" ,	"Market order temporarily suspended. Please send limit order    ");
       errorCode.put("1217" ,	"Order was sent at ±5% of the current market price. Please resend    ");
       errorCode.put("1218" ,	"Place order failed. Please try again later    ");

    }
}
